DATA:
  NAME: "lits"
  INPUTS_PATH: "/home/aistudio/data/scan_temp"
  LABELS_PATH: "/home/aistudio/data/label_temp"
  PREP_PATH: "/home/aistudio/data/preprocess"
PREP:
  FRONT: 1
  WINDOW: False
  CROP: False
  THRESH: 1024
  SIZE: (512, 512, -1)
  BATCH_SIZE: 16
TRAIN:
  ARCHITECTURE: "unet_plain"
  BATCH_SIZE: 1
  SNAPSHOT_BATCH: 600
  DISP_BATCH: 1
  REG_TYPE: L1
  REG_COEFF: 1e-6
AUG:
  ROTATE:
    RATIO: (0, 0.2, 0)
    RANGE: (0,(-15, -16),0)
  FLIP:
    RATIO: (0, 0, 0)
  WINDOWLIZE: True
  WWWC: (400, 0)
  ZOOM:
    RATIO: (0, 0.3, 0.3)
    RANGE: (0, (0.8, 1.0), (0.8, 1.0))
INFER:
  PATH:
    INPUT: "/home/aistudio/data/inference"
    OUTPUT: "/home/aistudio/data/infer_lab"
    PARAM: "/home/aistudio/param/liver_inf"
  BATCH_SIZE: 196
EVAL:
  PATH:
    SEG: "/home/aistudio/data/infer_lab"
    GT: "/home/aistudio/data/label"
  METRICS: [
      "IOU",
      "Dice",
      "TP",
      "TN",
      "Precision",
      "Recall",
      "Sensitivity",
      "Specificity",
      "Accuracy",
    ]
