DATA:
  NAME: "optic"
  INPUTS_PATH: "/home/aistudio/optic/image"
  LABELS_PATH: "/home/aistudio/optic/label"
  PREP_PATH: "/home/aistudio/optic/prep"
TRAIN:
  ARCHITECTURE: "res_unet"
  BATCH_SIZE: 8
  SNAPSHOT_BATCH: 30
  DISP_BATCH: 1
